version: '3.8'

services:
  uav-sim:
    build:
      context: ../../
      dockerfile: docker/simulation/Dockerfile
    container_name: uav_simulation
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .:/home/uav/workspace
    privileged: true
    stdin_open: true
    tty: true
